package com.stream.prettylive.streaming.internal.sdk.effect.bean;

public enum BeautyType {
    // Beauty
    // Beauty - Basic
    BASIC_RESET, BASIC_SMOOTHING, BASIC_SKIN_TONE, BASIC_BLUSHER, BASIC_SHARPENING, BASIC_WRINKLES, BASIC_DARK_CIRCLES

    // Beauty - Advanced
    , ADVANCED_RESET, ADVANCED_FACE_SLIMMING, ADVANCED_EYES_ENLARGING, ADVANCED_EYES_BRIGHTENING, ADVANCED_CHIN_LENGTHENING, ADVANCED_MOUTH_RESHAPE, ADVANCED_TEETH_WHITENING, ADVANCED_NOSE_SLIMMING, ADVANCED_NOSE_LENGTHENING, ADVANCED_FACE_SHORTENING, ADVANCED_MANDIBLE_SLIMMING, ADVANCED_CHEEKBONE_SLIMMING, ADVANCED_FOREHEAD_SLIMMING

    // Beauty - Makeup
    // Beauty - Makeup - Lipstick
    , MAKEUP_LIPSTICK_NONE, MAKEUP_LIPSTICK_CAMEO_PINK, MAKEUP_LIPSTICK_SWEET_ORANGE, MAKEUP_LIPSTICK_RUST_RED, MAKEUP_LIPSTICK_CORAL, MAKEUP_LIPSTICK_RED_VELVET

    // Beauty - Makeup - Blusher
    , MAKEUP_BLUSHER_NONE, MAKEUP_BLUSHER_SLIGHTLY_DRUNK, MAKEUP_BLUSHER_PEACH, MAKEUP_BLUSHER_MILKY_ORANGE, MAKEUP_BLUSHER_APRICOT_PINK, MAKEUP_BLUSHER_SWEET_ORANGE

    // Beauty - Makeup - Eyelashes
    , MAKEUP_EYELASHES_NONE, MAKEUP_EYELASHES_NATURAL, MAKEUP_EYELASHES_TENDER, MAKEUP_EYELASHES_CURL, MAKEUP_EYELASHES_EVERLONG, MAKEUP_EYELASHES_THICK

    // Beauty - Makeup - Eyeliner
    , MAKEUP_EYELINER_NONE, MAKEUP_EYELINER_NATURAL, MAKEUP_EYELINER_CAT_EYE, MAKEUP_EYELINER_NAUGHTY, MAKEUP_EYELINER_INNOCENT, MAKEUP_EYELINER_DIGNIFIED

    // Beauty - Makeup - Eyeshadow
    , MAKEUP_EYESHADOW_NONE, MAKEUP_EYESHADOW_PINK_MIST, MAKEUP_EYESHADOW_SHIMMER_PINK, MAKEUP_EYESHADOW_TEA_BROWN, MAKEUP_EYESHADOW_BRIGHT_ORANGE, MAKEUP_EYESHADOW_MOCHA_BROWN

    // Beauty - Makeup - Colored Contacts
    , MAKEUP_COLORED_CONTACTS_NONE, MAKEUP_COLORED_CONTACTS_DARKNIGHT_BLACK, MAKEUP_COLORED_CONTACTS_STARRY_BLUE, MAKEUP_COLORED_CONTACTS_BROWN_GREEN, MAKEUP_COLORED_CONTACTS_LIGHTS_BROWN, MAKEUP_COLORED_CONTACTS_CHOCOLATE_BROWN

    // Beauty - Style-Makeup
    , STYLE_MAKEUP_NONE, STYLE_MAKEUP_INNOCENT_EYES, STYLE_MAKEUP_MILKY_EYES, STYLE_MAKEUP_CUTIE_COOL, STYLE_MAKEUP_PURE_SEXY, STYLE_MAKEUP_FLAWLESS

    // Filters
    // Filters - Natural
    , FILTER_NONE, FILTER_NATURAL_CREAMY, FILTER_NATURAL_BRIGHTEN, FILTER_NATURAL_FRESH, FILTER_NATURAL_AUTUMN

    // Filters - Gray
    , FILTER_GRAY_MONET, FILTER_GRAY_NIGHT, FILTER_GRAY_FILMLIKE

    // Filters - Dreamy
    , FILTER_DREAMY_SUNSET, FILTER_DREAMY_COZILY, FILTER_DREAMY_SWEET

    // Stickers
    , STICKER_NONE, STICKER_ANIMAL, STICKER_DIVE, STICKER_CAT, STICKER_WATERMELON, STICKER_DEER, STICKER_COOL_GIRL, STICKER_CLOWN, STICKER_CLAW_MACHINE, STICKER_SAILOR_MOON

    // background
    //    , backgroundGreenScreenSegmentation
    , BACKGROUND_NONE, BACKGROUND_PORTRAIT_SEGMENTATION, BACKGROUND_MOSAICING, BACKGROUND_GAUSSIAN_BLUR;
}
